# Generated by Django 3.0.7 on 2021-10-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211025_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_client',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_teacher',
        ),
    ]
