# Generated by Django 3.0.7 on 2021-10-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20211021_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('files', models.FileField(upload_to='documents/cases2/', verbose_name='Casos')),
                ('description', models.CharField(max_length=300)),
                ('type_status', models.CharField(choices=[('L', 'Legal'), ('F', 'Financiera'), ('A', 'Ambos')], default='', max_length=1)),
                ('status', models.CharField(choices=[('D', 'Disponible'), ('A', 'Asignado'), ('S', 'Solicitud Cierre'), ('C', 'Cerrado')], default='Disponible', max_length=1)),
                ('chat_preference', models.CharField(choices=[('0', 'ChatApp'), ('1', 'Llamada'), ('2', 'Ambas')], default='', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cierre')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
            },
        ),
    ]
