# Generated by Django 3.0.7 on 2021-10-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20211022_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case2',
            name='case_client',
        ),
        migrations.AddField(
            model_name='case2',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Client'),
        ),
    ]
