# Generated by Django 3.0.7 on 2021-10-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_auto_20211024_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_client',
        ),
        migrations.AddField(
            model_name='case2',
            name='clien_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
