# Generated by Django 3.0.7 on 2021-10-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20211024_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case2',
            name='clien_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
