# Generated by Django 3.0.7 on 2021-10-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20211024_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case2',
            old_name='clien_id',
            new_name='client_ide',
        ),
    ]
