# Generated by Django 3.0.7 on 2021-11-17 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20211110_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='files',
            field=models.FileField(default=1, upload_to='documents/cases/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='careers',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institucion Educacion Superior'),
        ),
    ]
