# Generated by Django 3.0.7 on 2021-11-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_auto_20211117_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='files',
            field=models.FileField(upload_to='documents/cases/', verbose_name='Archivos'),
        ),
    ]
