# Generated by Django 3.0.7 on 2021-11-17 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_auto_20211117_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='files',
            field=models.FileField(upload_to='documents/cases/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivos'),
        ),
    ]
