# Generated by Django 3.0.7 on 2021-10-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_auto_20211024_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case2',
            name='files',
            field=models.FileField(upload_to='documents/cases2/', verbose_name='Archivos'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
